name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:      # lets you run it manually
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: gtejaswi2212
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push snake
        run: |
          mkdir -p dist
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg
          git commit -m "chore: update snake" || echo "no changes to commit"
          git push
